# Generated by Django 4.0.5 on 2022-07-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=12)),
                ('mail', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_face', models.CharField(max_length=120)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакты',
            },
        ),
    ]
