# Generated by Django 4.0.5 on 2022-07-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_clientmodel_fac_adress_clientmodel_ur_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
