# Generated by Django 4.0.5 on 2022-07-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_clientmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='mail',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
    ]
