# Generated by Django 4.0.5 on 2022-07-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_clientmodel_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='phone',
            field=models.IntegerField(max_length=12),
        ),
    ]
