# Generated by Django 4.0.5 on 2022-07-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_clientmodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
