# Generated by Django 4.0.5 on 2022-07-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_clientmodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
