# Generated by Django 4.0.5 on 2022-07-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_clientmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='phone3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
