# Generated by Django 4.0.5 on 2022-07-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_clientmodel_phone2_clientmodel_phone3'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
