# Generated by Django 4.0.5 on 2022-07-12 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'профайл юзера', 'verbose_name_plural': 'профайлы юзеров'},
        ),
    ]
