# Generated by Django 4.0.5 on 2022-07-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('DR', 'директор'), ('MP', 'менеджер по продажам'), ('BG', 'бухгалтер'), ('MD', 'менеджер по работе с документами')], max_length=40),
        ),
    ]
