# Generated by Django 4.0.5 on 2022-07-06 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productmodel_product_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'группа продукта',
            },
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.groupproductmodel'),
        ),
    ]
