# Generated by Django 4.0.5 on 2022-07-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_groupproductmodel_alter_productmodel_product_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupproductmodel',
            options={'verbose_name': 'группа продукта', 'verbose_name_plural': 'группы продуктов'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'перечень продукта', 'verbose_name_plural': 'перечень продуктов'},
        ),
    ]
