# Generated by Django 4.0.5 on 2022-07-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_groupproductmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentproductmodel',
            options={'verbose_name': 'документ', 'verbose_name_plural': 'документы'},
        ),
    ]
