# Generated by Django 4.0.5 on 2022-07-06 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_documentproductmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.groupproductmodel'),
        ),
    ]
