# Generated by Django 4.0.5 on 2022-07-12 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0010_clientmodel_inn'),
        ('product', '0009_alter_productmodel_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraidModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.clientmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productmodel')),
            ],
            options={
                'verbose_name': 'сделка',
                'verbose_name_plural': 'сделки',
            },
        ),
    ]
